### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, -1)

### ISSUE THREAD

**Issue by romanianborg** [atom/go-to-line#23] opened 2015-07-02 21:05 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [go-to-line](https://github.com/atom/go-to-line) package, v0.30.0

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, -1)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, -1)
  at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:693:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:2530:33)
  at GoToLineView.module.exports.GoToLineView.confirm (/usr/share/atom/resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:116:14)
  at atom-text-editor.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:55:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -4:23.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -4:22.9.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -4:21.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:03.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:57.5.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:56.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:17.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:17.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:16.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:15.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:05.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:05.0 go-to-line:toggle (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-07-06 19:50
I believe this is a duplicate of #22

**Closed by kevinsawicki** 2015-07-06 19:50 UTC
Labels: bug, uncaught-exception
